{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "LAPTOP-VA2T4DUA\\MSSQLSERVER01",
            "database": "WideWorldImportersDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "laptop-va2t4dua\\mssqlserver01;WideWorldImportersDW",
          "Username": "Fox",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Dimension City",
        "columns": [
          {
            "name": "City Key",
            "dataType": "int64",
            "sourceColumn": "City Key"
          },
          {
            "name": "WWI City ID",
            "dataType": "int64",
            "sourceColumn": "WWI City ID"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State Province",
            "dataType": "string",
            "sourceColumn": "State Province"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "Sales Territory"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          },
          {
            "name": "Subregion",
            "dataType": "string",
            "sourceColumn": "Subregion"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "Latest Recorded Population",
            "dataType": "int64",
            "sourceColumn": "Latest Recorded Population"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Dimension_City = Source{[Schema=\"Dimension\",Item=\"City\"]}[Data]",
                "in",
                "    Dimension_City"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography",
            "levels": [
              {
                "name": "Continent",
                "ordinal": 0,
                "column": "Continent"
              },
              {
                "name": "Country",
                "ordinal": 1,
                "column": "Country"
              },
              {
                "name": "State Province",
                "ordinal": 2,
                "column": "State Province"
              },
              {
                "name": "City",
                "ordinal": 3,
                "column": "City"
              }
            ]
          },
          {
            "name": "Sales Region",
            "levels": [
              {
                "name": "Region",
                "ordinal": 0,
                "column": "Region"
              },
              {
                "name": "Subregion",
                "ordinal": 1,
                "column": "Subregion"
              },
              {
                "name": "Sales Territory",
                "ordinal": 2,
                "column": "Sales Territory"
              },
              {
                "name": "State Province",
                "ordinal": 3,
                "column": "State Province"
              },
              {
                "name": "City",
                "ordinal": 4,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "Dimension Customer",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "int64",
            "sourceColumn": "Customer Key"
          },
          {
            "name": "WWI Customer ID",
            "dataType": "int64",
            "sourceColumn": "WWI Customer ID"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer"
          },
          {
            "name": "Bill To Customer",
            "dataType": "string",
            "sourceColumn": "Bill To Customer"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Buying Group",
            "dataType": "string",
            "sourceColumn": "Buying Group"
          },
          {
            "name": "Primary Contact",
            "dataType": "string",
            "sourceColumn": "Primary Contact"
          },
          {
            "name": "Postal Code",
            "dataType": "string",
            "sourceColumn": "Postal Code"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Dimension_Customer = Source{[Schema=\"Dimension\",Item=\"Customer\"]}[Data]",
                "in",
                "    Dimension_Customer"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total customer count",
            "expression": "COUNT('Dimension Customer'[Bill To Customer])",
            "formatString": "0"
          },
          {
            "name": "Total Tailspin Toys customers",
            "expression": "COUNTROWS(FILTER('Dimension Customer', 'Dimension Customer'[Buying Group] = \"Tailspin Toys\"))",
            "formatString": "0"
          },
          {
            "name": "% of customers are Tailspin Toys",
            "expression": "COUNTROWS(FILTER('Dimension Customer', 'Dimension Customer'[Buying Group] = \"Tailspin Toys\")) / COUNT('Dimension Customer'[Bill To Customer])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Current customer count",
            "expression": "COUNTROWS(FILTER('Dimension Customer', 'Dimension Customer'[Valid To] > TODAY()))",
            "formatString": "0"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Category",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "Category"
              },
              {
                "name": "Buying Group",
                "ordinal": 1,
                "column": "Buying Group"
              },
              {
                "name": "Bill To Customer",
                "ordinal": 2,
                "column": "Bill To Customer"
              },
              {
                "name": "Customer",
                "ordinal": 3,
                "column": "Customer"
              }
            ]
          }
        ]
      },
      {
        "name": "Dimension Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Day Number",
            "dataType": "int64",
            "sourceColumn": "Day Number"
          },
          {
            "name": "Day",
            "dataType": "string",
            "sourceColumn": "Day"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Short Month",
            "dataType": "string",
            "sourceColumn": "Short Month"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "sourceColumn": "Calendar Month Number"
          },
          {
            "name": "Calendar Month Label",
            "dataType": "string",
            "sourceColumn": "Calendar Month Label"
          },
          {
            "name": "Calendar Year",
            "dataType": "int64",
            "sourceColumn": "Calendar Year"
          },
          {
            "name": "Calendar Year Label",
            "dataType": "string",
            "sourceColumn": "Calendar Year Label"
          },
          {
            "name": "Fiscal Month Number",
            "dataType": "int64",
            "sourceColumn": "Fiscal Month Number"
          },
          {
            "name": "Fiscal Month Label",
            "dataType": "string",
            "sourceColumn": "Fiscal Month Label"
          },
          {
            "name": "Fiscal Year",
            "dataType": "int64",
            "sourceColumn": "Fiscal Year"
          },
          {
            "name": "Fiscal Year Label",
            "dataType": "string",
            "sourceColumn": "Fiscal Year Label"
          },
          {
            "name": "ISO Week Number",
            "dataType": "int64",
            "sourceColumn": "ISO Week Number"
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              " SWITCH(",
              "    TRUE(), ",
              "    AND ([Calendar Month Number] > 0, [Calendar Month Number] < 4), \"Q1\", ",
              "    [Calendar Month Number] < 7, \"Q2\", ",
              "    [Calendar Month Number] < 10, \"Q3\", ",
              "    [Calendar Month Number] < 13, \"Q4\",",
              "    \"Undefined\")",
              "    "
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Dimension_Date = Source{[Schema=\"Dimension\",Item=\"Date\"]}[Data]",
                "in",
                "    Dimension_Date"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Calendar Year",
                "ordinal": 0,
                "column": "Calendar Year Label"
              },
              {
                "name": "Calendar Month",
                "ordinal": 2,
                "column": "Calendar Month Label"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              }
            ]
          },
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Label"
              },
              {
                "name": "Fiscal Month",
                "ordinal": 1,
                "column": "Fiscal Month Label"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              },
              {
                "name": "Quarter",
                "ordinal": 2,
                "column": "Quarter"
              }
            ]
          },
          {
            "name": "ISO Week",
            "levels": [
              {
                "name": "ISO Week Number",
                "ordinal": 0,
                "column": "ISO Week Number"
              },
              {
                "name": "Date",
                "ordinal": 1,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "Dimension Employee",
        "columns": [
          {
            "name": "Employee Key",
            "dataType": "int64",
            "sourceColumn": "Employee Key"
          },
          {
            "name": "WWI Employee ID",
            "dataType": "int64",
            "sourceColumn": "WWI Employee ID"
          },
          {
            "name": "Employee",
            "dataType": "string",
            "sourceColumn": "Employee"
          },
          {
            "name": "Preferred Name",
            "dataType": "string",
            "sourceColumn": "Preferred Name"
          },
          {
            "name": "Is Salesperson",
            "dataType": "boolean",
            "sourceColumn": "Is Salesperson"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Dimension_Employee = Source{[Schema=\"Dimension\",Item=\"Employee\"]}[Data]",
                "in",
                "    Dimension_Employee"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "% of current employees that are salespeople",
            "expression": "COUNTROWS(FILTER('Dimension Employee', AND('Dimension Employee'[Valid To] > TODAY(), 'Dimension Employee'[Is Salesperson] = TRUE()))) / COUNTROWS(FILTER('Dimension Employee', 'Dimension Employee'[Valid To] > TODAY()))",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          }
        ]
      },
      {
        "name": "Dimension Stock Item",
        "columns": [
          {
            "name": "Stock Item Key",
            "dataType": "int64",
            "sourceColumn": "Stock Item Key"
          },
          {
            "name": "WWI Stock Item ID",
            "dataType": "int64",
            "sourceColumn": "WWI Stock Item ID"
          },
          {
            "name": "Stock Item",
            "dataType": "string",
            "sourceColumn": "Stock Item"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Selling Package",
            "dataType": "string",
            "sourceColumn": "Selling Package"
          },
          {
            "name": "Buying Package",
            "dataType": "string",
            "sourceColumn": "Buying Package"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "Lead Time Days",
            "dataType": "int64",
            "sourceColumn": "Lead Time Days"
          },
          {
            "name": "Quantity Per Outer",
            "dataType": "int64",
            "sourceColumn": "Quantity Per Outer"
          },
          {
            "name": "Is Chiller Stock",
            "dataType": "boolean",
            "sourceColumn": "Is Chiller Stock"
          },
          {
            "name": "Barcode",
            "dataType": "string",
            "sourceColumn": "Barcode"
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "sourceColumn": "Tax Rate"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Recommended Retail Price",
            "dataType": "double",
            "sourceColumn": "Recommended Retail Price"
          },
          {
            "name": "Typical Weight Per Unit",
            "dataType": "double",
            "sourceColumn": "Typical Weight Per Unit"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    #\"Dimension_Stock Item\" = Source{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data]",
                "in",
                "    #\"Dimension_Stock Item\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "% of stock items are Northwind",
            "expression": " COUNT('NorthWind Stock Item'[Stock Item Key]) / COUNT('Dimension Stock Item'[Stock Item Key])",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "kpi": {
              "targetExpression": "0,15",
              "targetFormatString": "0.00 %;-0.00 %;0.00 %",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Dimension Stock Item'[% of stock items are Northwind] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.075,-1,",
                "\t                If(x<0.15,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.075"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "0.15"
                }
              ]
            }
          },
          {
            "name": "Chiller stock percentage",
            "expression": "COUNTAX(FILTER('Dimension Stock Item', [Is Chiller Stock] = TRUE()), TRUE()) / COUNT('Dimension Stock Item'[Stock Item Key])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Unit price average",
            "expression": "AVERAGE('Dimension Stock Item'[Unit Price])",
            "formatString": "0.00"
          },
          {
            "name": "Recommended retail price average",
            "expression": "AVERAGE('Dimension Stock Item'[Recommended Retail Price])",
            "formatString": "0.00"
          },
          {
            "name": "Total items",
            "expression": "COUNT('Dimension Stock Item'[Stock Item Key])"
          },
          {
            "name": "Total current items",
            "expression": "COUNTROWS(FILTER('Dimension Stock Item', 'Dimension Stock Item'[Valid To] > TODAY()))"
          },
          {
            "name": "% of stock items are Northwind goal",
            "expression": "0.15",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          }
        ],
        "hierarchies": [
          {
            "name": "Item Brand",
            "levels": [
              {
                "name": "Brand",
                "ordinal": 3,
                "column": "Brand"
              },
              {
                "name": "Stock Item",
                "ordinal": 0,
                "column": "Stock Item"
              },
              {
                "name": "Color",
                "ordinal": 1,
                "column": "Color"
              },
              {
                "name": "Size",
                "ordinal": 2,
                "column": "Size"
              }
            ]
          }
        ]
      },
      {
        "name": "Fact Sale",
        "columns": [
          {
            "name": "Sale Key",
            "dataType": "int64",
            "sourceColumn": "Sale Key"
          },
          {
            "name": "City Key",
            "dataType": "int64",
            "sourceColumn": "City Key"
          },
          {
            "name": "Customer Key",
            "dataType": "int64",
            "sourceColumn": "Customer Key"
          },
          {
            "name": "Bill To Customer Key",
            "dataType": "int64",
            "sourceColumn": "Bill To Customer Key"
          },
          {
            "name": "Stock Item Key",
            "dataType": "int64",
            "sourceColumn": "Stock Item Key"
          },
          {
            "name": "Invoice Date Key",
            "dataType": "dateTime",
            "sourceColumn": "Invoice Date Key"
          },
          {
            "name": "Delivery Date Key",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date Key"
          },
          {
            "name": "Salesperson Key",
            "dataType": "int64",
            "sourceColumn": "Salesperson Key"
          },
          {
            "name": "WWI Invoice ID",
            "dataType": "int64",
            "sourceColumn": "WWI Invoice ID"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "Package",
            "dataType": "string",
            "sourceColumn": "Package"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "sourceColumn": "Tax Rate"
          },
          {
            "name": "Total Excluding Tax",
            "dataType": "double",
            "sourceColumn": "Total Excluding Tax"
          },
          {
            "name": "Tax Amount",
            "dataType": "double",
            "sourceColumn": "Tax Amount"
          },
          {
            "name": "Profit",
            "dataType": "double",
            "sourceColumn": "Profit"
          },
          {
            "name": "Total Including Tax",
            "dataType": "double",
            "sourceColumn": "Total Including Tax"
          },
          {
            "name": "Total Dry Items",
            "dataType": "int64",
            "sourceColumn": "Total Dry Items"
          },
          {
            "name": "Total Chiller Items",
            "dataType": "int64",
            "sourceColumn": "Total Chiller Items"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          },
          {
            "type": "calculated",
            "name": "Delivery Time In Hours",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " DATEDIFF([Invoice Date Key], [Delivery Date Key], HOUR)"
          }
        ],
        "partitions": [
          {
            "name": "All data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Fact_Sale = Source{[Schema=\"Fact\",Item=\"Sale\"]}[Data]",
                "in",
                "    Fact_Sale"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                  "    Fact_Sale = Source{[Schema=\"Fact\",Item=\"Sale\"]}[Data]",
                  "in",
                  "    Fact_Sale</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Quantity sum",
            "expression": "SUM('Fact Sale'[Quantity])",
            "formatString": "0"
          },
          {
            "name": "Quantity average",
            "expression": "AVERAGE('Fact Sale'[Quantity])",
            "formatString": "0.00"
          },
          {
            "name": "Dry items sum",
            "expression": "SUM('Fact Sale'[Total Dry Items])",
            "formatString": "0"
          },
          {
            "name": "Chiller items sum",
            "expression": "SUM('Fact Sale'[Total Chiller Items])",
            "formatString": "0"
          },
          {
            "name": "Dry items average",
            "expression": "AVERAGE('Fact Sale'[Total Dry Items])",
            "formatString": "0.00"
          },
          {
            "name": "Chiller items average",
            "expression": "AVERAGE('Fact Sale'[Total Chiller Items])",
            "formatString": "0.00"
          },
          {
            "name": "Total profit sum",
            "expression": "SUM('Fact Sale'[Profit])",
            "formatString": "0.00"
          },
          {
            "name": "Total profit average",
            "expression": "AVERAGE('Fact Sale'[Profit])",
            "formatString": "0.00"
          },
          {
            "name": "Profit YTD",
            "expression": "TOTALYTD(SUM('Fact Sale'[Profit]), 'Dimension Date'[Date])"
          },
          {
            "name": "Chiller items %",
            "expression": "[Chiller items sum] / ([Dry items sum] + [Chiller items sum])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Dry items %",
            "expression": "[Dry items sum] / ([Dry items sum] + [Chiller items sum])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Delivery time average (in hours)",
            "expression": "AVERAGE('Fact Sale'[Delivery Time In Hours])",
            "formatString": "0.00",
            "kpi": {
              "targetExpression": "48",
              "targetFormatString": "0.00",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Fact Sale'[Delivery time average (in hours)] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<24,-1,",
                "\t                If(x<36,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "24"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "36"
                }
              ]
            }
          }
        ]
      },
      {
        "name": "Fact Purchase",
        "columns": [
          {
            "name": "Purchase Key",
            "dataType": "int64",
            "sourceColumn": "Purchase Key"
          },
          {
            "name": "Date Key",
            "dataType": "dateTime",
            "sourceColumn": "Date Key"
          },
          {
            "name": "Supplier Key",
            "dataType": "int64",
            "sourceColumn": "Supplier Key"
          },
          {
            "name": "Stock Item Key",
            "dataType": "int64",
            "sourceColumn": "Stock Item Key"
          },
          {
            "name": "WWI Purchase Order ID",
            "dataType": "int64",
            "sourceColumn": "WWI Purchase Order ID"
          },
          {
            "name": "Ordered Outers",
            "dataType": "int64",
            "sourceColumn": "Ordered Outers"
          },
          {
            "name": "Ordered Quantity",
            "dataType": "int64",
            "sourceColumn": "Ordered Quantity"
          },
          {
            "name": "Received Outers",
            "dataType": "int64",
            "sourceColumn": "Received Outers"
          },
          {
            "name": "Package",
            "dataType": "string",
            "sourceColumn": "Package"
          },
          {
            "name": "Is Order Finalized",
            "dataType": "boolean",
            "sourceColumn": "Is Order Finalized"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Fact_Purchase = Source{[Schema=\"Fact\",Item=\"Purchase\"]}[Data]",
                "in",
                "    Fact_Purchase"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Ordered quantity sum",
            "expression": "SUM('Fact Purchase'[Ordered Quantity])",
            "formatString": "0"
          },
          {
            "name": "Ordered quantity average",
            "expression": "AVERAGE('Fact Purchase'[Ordered Quantity])",
            "formatString": "0.00"
          },
          {
            "name": "Carton package count",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Package] = \"Carton\"))",
            "formatString": "0"
          },
          {
            "name": "Each package count",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Package] = \"Each\"))",
            "formatString": "0"
          },
          {
            "name": "Carton package percentage",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Package] = \"Carton\")) / COUNT('Fact Purchase'[Package])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Each package percentage",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Package] = \"Each\")) / COUNT('Fact Purchase'[Package])",
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Finalized orders percentage",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Is Order Finalized] = TRUE())) / COUNTA('Fact Purchase'[Is Order Finalized])",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "kpi": {
              "targetExpression": "99",
              "targetFormatString": "0.00 %;-0.00 %;0.00 %",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Fact Purchase'[Finalized orders percentage] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<90,-1,",
                "\t                If(x<94.5,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "90"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "94.5"
                }
              ]
            }
          },
          {
            "name": "Finalized orders count",
            "expression": "COUNTROWS(FILTER('Fact Purchase', 'Fact Purchase'[Is Order Finalized] = TRUE()))",
            "formatString": "0"
          },
          {
            "name": "Orders count",
            "expression": "COUNTA('Fact Purchase'[Is Order Finalized])",
            "formatString": "0"
          }
        ]
      },
      {
        "name": "NorthWind Stock Item",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Stock Item Key",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Stock Item Key]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WWI Stock Item ID",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[WWI Stock Item ID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Stock Item",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Stock Item]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Color",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Color]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Selling Package",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Selling Package]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Buying Package",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Buying Package]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Brand",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Brand]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Size",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Size]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Lead Time Days",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Lead Time Days]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quantity Per Outer",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Quantity Per Outer]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Is Chiller Stock",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Is Chiller Stock]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "Barcode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Barcode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tax Rate",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Tax Rate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Unit Price",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Unit Price]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Recommended Retail Price",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Recommended Retail Price]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Typical Weight Per Unit",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Typical Weight Per Unit]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Valid From",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Valid From]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Valid To",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Valid To]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Lineage Key",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Lineage Key]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " FILTER('Dimension Stock Item', [Brand] = \"Northwind\")"
            }
          }
        ]
      },
      {
        "name": "Dimension Supplier",
        "columns": [
          {
            "name": "Supplier Key",
            "dataType": "int64",
            "sourceColumn": "Supplier Key"
          },
          {
            "name": "WWI Supplier ID",
            "dataType": "int64",
            "sourceColumn": "WWI Supplier ID"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Primary Contact",
            "dataType": "string",
            "sourceColumn": "Primary Contact"
          },
          {
            "name": "Supplier Reference",
            "dataType": "string",
            "sourceColumn": "Supplier Reference"
          },
          {
            "name": "Payment Days",
            "dataType": "int64",
            "sourceColumn": "Payment Days"
          },
          {
            "name": "Postal Code",
            "dataType": "string",
            "sourceColumn": "Postal Code"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-30T6BRV\\DOWSQL2022;WideWorldImportersDW\",",
                "    Dimension_Supplier = Source{[Schema=\"Dimension\",Item=\"Supplier\"]}[Data]",
                "in",
                "    Dimension_Supplier"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Current supplier count",
            "expression": "COUNTROWS(FILTER('Dimension Supplier', 'Dimension Supplier'[Valid To] > TODAY()))",
            "formatString": "0"
          },
          {
            "name": "Payment days average",
            "expression": "AVERAGE('Dimension Supplier'[Payment Days])",
            "formatString": "0.00"
          }
        ],
        "hierarchies": [
          {
            "name": "Category Supplier",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "Category"
              },
              {
                "name": "Supplier",
                "ordinal": 1,
                "column": "Supplier"
              }
            ]
          }
        ]
      },
      {
        "name": "Item Per Supplier",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Supplier",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Supplier[Supplier]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Stock Item",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Dimension Stock Item[Stock Item]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Items Per Supplier",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Items Per Supplier]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "SUMMARIZECOLUMNS('Dimension Stock Item'[Stock Item], 'Dimension Supplier'[Supplier], \"Items Per Supplier\", COUNT('Fact Purchase'[Stock Item Key]))"
            }
          }
        ]
      },
      {
        "name": "Annual Calculations",
        "calculationGroup": {
          "precedence": 25,
          "calculationItems": [
            {
              "name": "YTD",
              "expression": "CALCULATE(SELECTEDMEASURE(),DATESYTD('Dimension Date'[Date]))",
              "ordinal": 1
            },
            {
              "name": "Previous Year",
              "expression": "CALCULATE(SELECTEDMEASURE(),PREVIOUSYEAR('Dimension Date'[Date]))",
              "ordinal": 3
            },
            {
              "name": "Next Year",
              "expression": "CALCULATE(SELECTEDMEASURE(),NEXTYEAR('Dimension Date'[Date]))",
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Annual Metric",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Sort Order"
          },
          {
            "name": "Sort Order",
            "dataType": "int64",
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "851ade76-bb1d-41f4-b483-14c6064a699d",
        "fromTable": "Fact Sale",
        "fromColumn": "Bill To Customer Key",
        "toTable": "Dimension Customer",
        "toColumn": "Customer Key",
        "isActive": false
      },
      {
        "name": "70371595-1e18-4f05-b9c7-1e1645d00786",
        "fromTable": "Fact Purchase",
        "fromColumn": "Date Key",
        "toTable": "Dimension Date",
        "toColumn": "Date"
      },
      {
        "name": "c5173f6d-fff2-491d-8081-ceb035de248b",
        "fromTable": "Fact Sale",
        "fromColumn": "Delivery Date Key",
        "toTable": "Dimension Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "eec5405f-0c20-4865-9503-d596757016d1",
        "fromTable": "Fact Sale",
        "fromColumn": "Invoice Date Key",
        "toTable": "Dimension Date",
        "toColumn": "Date"
      },
      {
        "name": "fd7343d5-84ee-4c8d-b5ff-9fb9249b2053",
        "fromTable": "Fact Sale",
        "fromColumn": "Stock Item Key",
        "toTable": "Dimension Stock Item",
        "toColumn": "Stock Item Key"
      },
      {
        "name": "df4993bb-d4b3-4833-be29-f326f7fa74ad",
        "fromTable": "Fact Sale",
        "fromColumn": "City Key",
        "toTable": "Dimension City",
        "toColumn": "City Key"
      },
      {
        "name": "60c88862-e895-4b8f-ba7b-86eb7d425ea5",
        "fromTable": "Fact Sale",
        "fromColumn": "Customer Key",
        "toTable": "Dimension Customer",
        "toColumn": "Customer Key"
      },
      {
        "name": "fb560f66-9fd0-4f53-9072-6e16b82510b6",
        "fromTable": "Fact Sale",
        "fromColumn": "Salesperson Key",
        "toTable": "Dimension Employee",
        "toColumn": "Employee Key"
      },
      {
        "name": "5a684317-c120-4602-9f67-8289699c1f54",
        "fromTable": "Fact Purchase",
        "fromColumn": "Stock Item Key",
        "toTable": "Dimension Stock Item",
        "toColumn": "Stock Item Key"
      },
      {
        "name": "139cb526-d465-490a-9f9f-b19ad9641b48",
        "fromTable": "Fact Purchase",
        "fromColumn": "Supplier Key",
        "toTable": "Dimension Supplier",
        "toColumn": "Supplier Key"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}